services:
  library:
    image: lampirg/library:0.0.1
    build:
      context: library
      target: build
  discovery:
    image: lampirg/discovery:0.0.1
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 20s
      retries: 5
    build:
      context: discovery
      additional_contexts:
        animerecommendator-library: service:library
    environment:
      SERVER_PORT: 8080
    ports:
      - "8761:8080"
  recommendator:
    image: lampirg/recommendator:0.0.1
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 20s
      retries: 5
    build:
      context: recommendator
      additional_contexts:
        animerecommendator-library: service:library
    environment:
      SERVER_PORT: 8080
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: http://discovery:8080/eureka/
    ports:
      - "8081:8080"
    depends_on:
      discovery:
        condition: service_healthy
  mal:
    image: lampirg/mal:0.0.1
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 20s
      retries: 5
    build:
      context: mal
      additional_contexts:
        animerecommendator-library: service:library
    environment:
      SERVER_PORT: 8080
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: http://discovery:8080/eureka/
    ports:
      - "8082:8080"
    depends_on:
      discovery:
        condition: service_healthy
      recommendator:
        condition: service_healthy
  shikimori:
    image: lampirg/shikimori:0.0.1
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 20s
      retries: 5
    build:
      context: shikimori
      additional_contexts:
        animerecommendator-library: service:library
    environment:
      SERVER_PORT: 8080
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: http://discovery:8080/eureka/
    ports:
      - "8083:8080"
    depends_on:
      discovery:
        condition: service_healthy
      recommendator:
        condition: service_healthy
  anilist:
    image: lampirg/anilist:0.0.1
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 20s
      retries: 5
    build:
      context: anilist
      additional_contexts:
        animerecommendator-library: service:library
    environment:
      SERVER_PORT: 8080
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: http://discovery:8080/eureka/
    ports:
      - "8084:8080"
    depends_on:
      discovery:
        condition: service_healthy
      recommendator:
        condition: service_healthy
  frontend:
    image: lampirg/frontend:0.0.1
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 20s
      retries: 5
    build:
      context: frontend
      additional_contexts:
        animerecommendator-library: service:library
    environment:
      SERVER_PORT: 8080
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: http://discovery:8080/eureka/
    ports:
      - "8085:8080"
    depends_on:
      discovery:
        condition: service_healthy
      recommendator:
        condition: service_healthy