version: '2.1'
services:
  discovery:
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 5
    build: discovery
    environment:
      SERVER_PORT: 8080
    ports:
      - "8761:8080"
  recommendator:
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 5
    build: recommendator
    environment:
      SERVER_PORT: 8080
      DISCOVERY_URL: http://localhost:8080/eureka/
    ports:
      - "8081:8080"
    depends_on:
      discovery:
        condition: service_healthy
  mal:
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 5
    build: mal
    environment:
      SERVER_PORT: 8080
      DISCOVERY_URL: http://localhost:8080/eureka/
    ports:
      - "8082:8080"
    depends_on:
      discovery:
        condition: service_healthy
      recommendator:
        condition: service_healthy